In [1]:
import geopandas as gpd

In [30]:
file = gpd.read_file('invalid_poly.geojson', engine='pyogrio')
file

,ogc_fid,fid,zone,mean,max,min,sum,std,var,count,type,geometry
0,5184,13000130,13000130.0,0.894444,1.0,0.0,161.0,0.307268,0.094414,180.0,Corn,"POLYGON ((113.82436 -8.36237, 113.82436 -8.362..."
1,5203,13000149,13000149.0,1.000000,1.0,1.0,7.0,0.000000,0.000000,7.0,Corn,"POLYGON ((113.82025 -8.36020, 113.82025 -8.360..."
2,5214,13000185,13000185.0,1.000000,1.0,1.0,30.0,0.000000,0.000000,30.0,Corn,"POLYGON ((113.82169 -8.36092, 113.82169 -8.360..."
3,6341,13024390,13024390.0,0.970588,1.0,0.0,33.0,0.168958,0.028547,34.0,Corn,"POLYGON ((113.77243 -8.35645, 113.77244 -8.356..."
4,6642,13027505,13027505.0,0.950000,1.0,0.0,38.0,0.217945,0.047500,40.0,Corn,"POLYGON ((113.77726 -8.36033, 113.77739 -8.360..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1173,656,12002604,12002604.0,1.000000,1.0,1.0,1.0,0.000000,0.000000,1.0,Corn,"POLYGON ((113.68617 -8.39326, 113.68617 -8.393..."
1174,657,12002605,12002605.0,1.000000,1.0,1.0,37.0,0.000000,0.000000,37.0,Corn,"POLYGON ((113.68614 -8.39339, 113.68614 -8.393..."
1175,2479,13031811,13031811.0,0.833333,1.0,0.0,15.0,0.372678,0.138889,18.0,Corn,"POLYGON ((113.73740 -8.39545, 113.73740 -8.395..."
1176,3858,17000659,17000659.0,0.916667,1.0,0.0,11.0,0.276385,0.076389,12.0,Corn,"POLYGON ((113.72380 -8.41058, 113.72380 -8.410..."
1177,4968,18000950,18000950.0,0.333333,1.0,0.0,1.0,0.471405,0.222222,3.0,Rice,"POLYGON ((113.75503 -8.41431, 113.75503 -8.414..."

In [31]:
file.geometry = file.geometry.make_valid()
file = file.explode(ignore_index=True)

In [37]:
file = file[file.geometry.type == 'Polygon']

In [39]:
file

,ogc_fid,fid,zone,mean,max,min,sum,std,var,count,type,geometry
0,5184,13000130,13000130.0,0.894444,1.0,0.0,161.0,0.307268,0.094414,180.0,Corn,"POLYGON ((113.82436 -8.36237, 113.82436 -8.362..."
1,5184,13000130,13000130.0,0.894444,1.0,0.0,161.0,0.307268,0.094414,180.0,Corn,"POLYGON ((113.82339 -8.36101, 113.82361 -8.361..."
2,5203,13000149,13000149.0,1.000000,1.0,1.0,7.0,0.000000,0.000000,7.0,Corn,"POLYGON ((113.82025 -8.36020, 113.82050 -8.360..."
3,5203,13000149,13000149.0,1.000000,1.0,1.0,7.0,0.000000,0.000000,7.0,Corn,"POLYGON ((113.82056 -8.36005, 113.82056 -8.360..."
4,5214,13000185,13000185.0,1.000000,1.0,1.0,30.0,0.000000,0.000000,30.0,Corn,"POLYGON ((113.82169 -8.36092, 113.82209 -8.361..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2358,2479,13031811,13031811.0,0.833333,1.0,0.0,15.0,0.372678,0.138889,18.0,Corn,"POLYGON ((113.73725 -8.39563, 113.73725 -8.395..."
2359,3858,17000659,17000659.0,0.916667,1.0,0.0,11.0,0.276385,0.076389,12.0,Corn,"POLYGON ((113.72381 -8.41058, 113.72411 -8.410..."
2360,3858,17000659,17000659.0,0.916667,1.0,0.0,11.0,0.276385,0.076389,12.0,Corn,"POLYGON ((113.72385 -8.41005, 113.72388 -8.409..."
2361,4968,18000950,18000950.0,0.333333,1.0,0.0,1.0,0.471405,0.222222,3.0,Rice,"POLYGON ((113.75506 -8.41427, 113.75506 -8.414..."
2362,4968,18000950,18000950.0,0.333333,1.0,0.0,1.0,0.471405,0.222222,3.0,Rice,"POLYGON ((113.75495 -8.41381, 113.75496 -8.413..."

In [40]:
file.to_file('fix_invalid.fgb')